"""Generate simulator-independent patient-cart RCM frame layouts."""

from __future__ import annotations

import argparse
from collections.abc import Mapping
import math
from pathlib import Path

import yaml


SPHERE_DIAMETER_M = 0.40
SPHERE_RADIUS_M = SPHERE_DIAMETER_M / 2.0

# Azimuth is measured in world XY from +X toward +Y.  Polar angle is measured
# down from +Z.  World -Y is the front of the default patient-cart layout.
DEFAULT_SPHERICAL_COORDINATES = {
    "PSM1": (180.0, 30.0),
    "PSM2": (0.0, 30.0),
    "PSM3": (0.0, 60.0),
    "ECM": (-90.0, 60.0),
}


def _normalize(values: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(value * value for value in values))
    return tuple(value / length for value in values)


def _shortest_arc_xyzw(
    source: tuple[float, float, float], target: tuple[float, float, float]
) -> tuple[float, float, float, float]:
    """Return a ROS-ordered quaternion rotating ``source`` onto ``target``."""
    source = _normalize(source)
    target = _normalize(target)
    cross = (
        source[1] * target[2] - source[2] * target[1],
        source[2] * target[0] - source[0] * target[2],
        source[0] * target[1] - source[1] * target[0],
    )
    dot = sum(a * b for a, b in zip(source, target))
    if dot < -0.999999:
        axis = (1.0, 0.0, 0.0) if abs(source[0]) < 0.9 else (0.0, 1.0, 0.0)
        cross = (
            source[1] * axis[2] - source[2] * axis[1],
            source[2] * axis[0] - source[0] * axis[2],
            source[0] * axis[1] - source[1] * axis[0],
        )
        quaternion = (*_normalize(cross), 0.0)
    else:
        quaternion = (*cross, 1.0 + dot)
    length = math.sqrt(sum(value * value for value in quaternion))
    return tuple(value / length for value in quaternion)


def rcm_position(
    azimuth_deg: float, polar_angle_deg: float, *, radius_m: float = SPHERE_RADIUS_M
) -> tuple[float, float, float]:
    """Return a point on the RCM sphere for the given spherical coordinates."""
    polar_angle = math.radians(polar_angle_deg)
    azimuth = math.radians(azimuth_deg)
    horizontal = radius_m * math.sin(polar_angle)
    return (
        horizontal * math.cos(azimuth),
        horizontal * math.sin(azimuth),
        radius_m * math.cos(polar_angle),
    )


def rcm_frame(
    azimuth_deg: float, polar_angle_deg: float, *, radius_m: float = SPHERE_RADIUS_M
) -> tuple[tuple[float, float, float], tuple[float, float, float, float]]:
    """Return a base frame whose +Z is the outward sphere normal.

    Virtual dVRK shafts point along local -Z, so their neutral direction is
    inward toward the center of the workspace sphere.
    """
    position = rcm_position(azimuth_deg, polar_angle_deg, radius_m=radius_m)
    inward = _normalize(tuple(-value for value in position))
    return position, _shortest_arc_xyzw((0.0, 0.0, -1.0), inward)


def spherical_coordinates(
    position: tuple[float, float, float] | list[float],
) -> tuple[float, float]:
    """Return azimuth/polar degrees for an RCM position on any radius sphere."""
    if len(position) != 3:
        raise ValueError("RCM position must contain exactly three values")
    x, y, z = (float(value) for value in position)
    radius = math.sqrt(x * x + y * y + z * z)
    if radius == 0.0:
        raise ValueError("RCM position cannot be the workspace center")
    polar = math.degrees(math.acos(max(-1.0, min(1.0, z / radius))))
    return math.degrees(math.atan2(y, x)), polar


def rcm_frames(
    coordinates: Mapping[str, tuple[float, float]] = DEFAULT_SPHERICAL_COORDINATES,
) -> dict[str, tuple[tuple[float, float, float], tuple[float, float, float, float]]]:
    """Generate named RCM frames in insertion order."""
    return {name: rcm_frame(*values) for name, values in coordinates.items()}


def _format(values: tuple[float, ...]) -> str:
    cleaned = (0.0 if abs(value) < 5e-10 else value for value in values)
    return "[" + ", ".join(f"{value:.9f}" for value in cleaned) + "]"


def _clean_values(values: tuple[float, ...]) -> list[float]:
    return [0.0 if abs(value) < 5e-10 else float(value) for value in values]


def yaml_frames(
    coordinates: Mapping[str, tuple[float, float]] = DEFAULT_SPHERICAL_COORDINATES,
) -> str:
    """Format frame declarations suitable for a simulator scene YAML file."""
    lines = [
        "# Generated by dvrk_simulator_base.cart_frames.",
        "# Positions are RCM/base poses in meters; orientations are ROS xyzw.",
        "frames:",
    ]
    for name, (position, orientation) in rcm_frames(coordinates).items():
        lines.append(
            f"  {name}: {{position: {_format(position)}, "
            f"orientation_xyzw: {_format(orientation)}}}"
        )
    return "\n".join(lines)


def update_scene_file(
    path: str | Path,
    coordinates: Mapping[str, tuple[float, float]] = DEFAULT_SPHERICAL_COORDINATES,
) -> None:
    """Replace the generated arm entries in a scene's ``scene.frames`` mapping."""
    source = Path(path).expanduser().resolve()
    with source.open("r", encoding="utf-8") as stream:
        document = yaml.safe_load(stream) or {}
    scene = document.get("scene") if isinstance(document, dict) else None
    if not isinstance(scene, dict):
        raise ValueError(f"{source}: expected a top-level 'scene' mapping")
    existing = scene.get("frames", {}) or {}
    if not isinstance(existing, dict):
        raise ValueError(f"{source}: scene.frames must be a mapping")
    frames = dict(existing)
    for name, (position, orientation) in rcm_frames(coordinates).items():
        frames[name] = {
            "position": _clean_values(position),
            "orientation_xyzw": _clean_values(orientation),
        }
    scene["frames"] = frames
    with source.open("w", encoding="utf-8") as stream:
        yaml.safe_dump(document, stream, sort_keys=False)


def load_scene_coordinates(path: str | Path) -> dict[str, tuple[float, float]]:
    """Load available PSM/ECM spherical coordinates from a scene YAML file."""
    source = Path(path).expanduser().resolve()
    with source.open("r", encoding="utf-8") as stream:
        document = yaml.safe_load(stream) or {}
    scene = document.get("scene") if isinstance(document, dict) else None
    if not isinstance(scene, dict):
        raise ValueError(f"{source}: expected a top-level 'scene' mapping")
    frames = scene.get("frames", {}) or {}
    if not isinstance(frames, dict):
        raise ValueError(f"{source}: scene.frames must be a mapping")
    coordinates = dict(DEFAULT_SPHERICAL_COORDINATES)
    for name in coordinates:
        frame = frames.get(name)
        if isinstance(frame, dict) and "position" in frame:
            coordinates[name] = spherical_coordinates(frame["position"])
    return coordinates


def main(arguments: list[str] | None = None) -> None:
    """Print default frames, or update an explicitly selected scene file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-s", "--scene", metavar="SCENE.yaml", help="update scene.frames in this YAML file"
    )
    options = parser.parse_args(arguments)
    if options.scene is None:
        print(yaml_frames())
        return
    try:
        update_scene_file(options.scene)
    except (FileNotFoundError, ValueError, yaml.YAMLError) as error:
        parser.error(str(error))
    print(f"updated cart RCM frames in {Path(options.scene).expanduser()}")
